spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.127.130:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  banner:
    location: classpath:lay.txt

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义属性
my:
  properties:
    author: LAY
    age: 23