spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.middleware-mysql.svc.cluster.local:3306/cms_db?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root